package memory

import (
	"context"
	"encoding/json"
	"math"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"testing"
)

// ---------- tokenizer parity (promoted from the Phase 0 spike) ----------

// The fixture in testdata was generated by HuggingFace `tokenizers` 0.23.1 via
// testdata/gen_fixture.py. This test is what caught two real spec-compliance bugs
// in sugarme/tokenizer (see LoadTokenizer): without it, every accented word would
// tokenize to [UNK] and retrieval would quietly degrade with no error anywhere.
//
// Because that library is not a faithful port, this suite must grow a case
// whenever a new text shape enters the corpus.

type parityFixture struct {
	MaxLen            int    `json:"max_len"`
	TokenizersVersion string `json:"tokenizers_version"`
	Cases             []struct {
		Name          string   `json:"name"`
		Text          string   `json:"text"`
		IDs           []int    `json:"ids"`
		Tokens        []string `json:"tokens"`
		TypeIDs       []int    `json:"type_ids"`
		AttentionMask []int    `json:"attention_mask"`
	} `json:"cases"`
	Truncation struct {
		Text           string `json:"text"`
		UntruncatedLen int    `json:"untruncated_len"`
		TruncatedIDs   []int  `json:"truncated_ids"`
		TruncatedLen   int    `json:"truncated_len"`
		FirstID        int    `json:"first_id"`
		LastID         int    `json:"last_id"`
	} `json:"truncation"`
}

func loadParityFixture(t *testing.T) parityFixture {
	t.Helper()
	b, err := os.ReadFile(filepath.Join("testdata", "tokenizer_parity.json"))
	if err != nil {
		t.Fatalf("read fixture: %v", err)
	}
	var f parityFixture
	if err := json.Unmarshal(b, &f); err != nil {
		t.Fatalf("parse fixture: %v", err)
	}
	return f
}

func TestTokenizerParity(t *testing.T) {
	p := TokenizerPath()
	if p == "" {
		t.Skip("tokenizer.json not provisioned")
	}
	fx := loadParityFixture(t)
	t.Logf("reference: HuggingFace tokenizers %s, %d cases", fx.TokenizersVersion, len(fx.Cases))

	tk, err := LoadTokenizer(p)
	if err != nil {
		t.Fatalf("LoadTokenizer: %v", err)
	}

	for _, c := range fx.Cases {
		t.Run(c.Name, func(t *testing.T) {
			enc, err := tk.EncodeSingle(c.Text, true)
			if err != nil {
				t.Fatalf("encode %q: %v", c.Text, err)
			}
			if !equalInts(enc.Ids, c.IDs) {
				t.Errorf("id mismatch for %q\n  got  %v (%v)\n  want %v (%v)",
					c.Text, enc.Ids, enc.Tokens, c.IDs, c.Tokens)
				return
			}
			if !equalInts(enc.TypeIds, c.TypeIDs) {
				t.Errorf("type_ids mismatch for %q: got %v want %v", c.Text, enc.TypeIds, c.TypeIDs)
			}
			if !equalInts(enc.AttentionMask, c.AttentionMask) {
				t.Errorf("attention_mask mismatch for %q", c.Text)
			}
		})
	}
}

// TestAccentStrippingRegression is the specific bug, called out on its own so a
// failure names the cause rather than just "case accents failed".
func TestAccentStrippingRegression(t *testing.T) {
	p := TokenizerPath()
	if p == "" {
		t.Skip("tokenizer.json not provisioned")
	}
	tk, err := LoadTokenizer(p)
	if err != nil {
		t.Fatal(err)
	}
	enc, err := tk.EncodeSingle("Café naïve résumé über", true)
	if err != nil {
		t.Fatal(err)
	}
	for _, tok := range enc.Tokens {
		if tok == "[UNK]" {
			t.Fatalf("accented text produced [UNK]: %v\n"+
				"sugarme/tokenizer applies StripAccents without NFD, and reads "+
				"strip_accents:null as false; LoadTokenizer must correct both", enc.Tokens)
		}
	}
	want := []string{"[CLS]", "cafe", "naive", "resume", "uber", "[SEP]"}
	if len(enc.Tokens) != len(want) {
		t.Fatalf("tokens = %v, want %v", enc.Tokens, want)
	}
	for i := range want {
		if enc.Tokens[i] != want[i] {
			t.Errorf("token %d = %q, want %q", i, enc.Tokens[i], want[i])
		}
	}
}

func equalInts(a, b []int) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

// ---------- fake embedder ----------

func TestFakeEmbedderDeterministicAndNormalized(t *testing.T) {
	f := NewFakeEmbedder()
	ctx := context.Background()

	a, err := f.EmbedPassages(ctx, []string{"the memory system stores chunks"})
	if err != nil {
		t.Fatal(err)
	}
	b, err := f.EmbedPassages(ctx, []string{"the memory system stores chunks"})
	if err != nil {
		t.Fatal(err)
	}
	if Cosine(a[0], b[0]) < 0.99999 {
		t.Error("fake embedder is not deterministic")
	}
	if n := vecNorm(a[0]); math.Abs(n-1) > 1e-5 {
		t.Errorf("norm = %v, want 1", n)
	}
	if len(a[0]) != EmbedDims {
		t.Errorf("dims = %d, want %d", len(a[0]), EmbedDims)
	}

	// Empty input must not produce a zero vector, which would break ranking.
	z, err := f.EmbedPassages(ctx, []string{""})
	if err != nil {
		t.Fatal(err)
	}
	if math.Abs(vecNorm(z[0])-1) > 1e-5 {
		t.Errorf("empty-text vector norm = %v, want 1", vecNorm(z[0]))
	}
}

// TestFakeEmbedderHasLexicalStructure is why the fake hashes features instead of
// returning random vectors: retrieval tests need "similar text scores higher" to
// hold without the real model.
func TestFakeEmbedderHasLexicalStructure(t *testing.T) {
	f := NewFakeEmbedder()
	ctx := context.Background()

	vs, err := f.EmbedPassages(ctx, []string{
		"the memory system stores chunks in duckdb",
		"the memory system stores chunks in a duckdb database",
		"leiden community detection groups sentences by topic",
	})
	if err != nil {
		t.Fatal(err)
	}
	near := Cosine(vs[0], vs[1])
	far := Cosine(vs[0], vs[2])
	if near <= far {
		t.Errorf("similar texts scored %.3f, dissimilar %.3f — no lexical structure", near, far)
	}
	t.Logf("similar=%.3f dissimilar=%.3f", near, far)
}

func vecNorm(v []float32) float64 {
	var s float64
	for _, x := range v {
		s += float64(x) * float64(x)
	}
	return math.Sqrt(s)
}

// ---------- resolution and unavailability ----------

func TestFindModelMissingIsUnavailable(t *testing.T) {
	t.Setenv("LOCALCHAT_MODEL_DIR", filepath.Join(t.TempDir(), "nope"))
	t.Setenv("HOME", t.TempDir())

	_, err := FindModel()
	if err == nil {
		t.Fatal("expected an error for a missing model")
	}
	if !Unavailable(err) {
		t.Errorf("error is not ErrUnavailable: %T %v", err, err)
	}
	if !strings.Contains(err.Error(), "memory unavailable") {
		t.Errorf("message should lead with the user-facing phrasing: %q", err.Error())
	}
	if !strings.Contains(err.Error(), "looked in") {
		t.Errorf("message should say where it looked: %q", err.Error())
	}
}

func TestFindORTReportsWhereItLooked(t *testing.T) {
	// Inject the inputs rather than mutating the environment: ORT initialization
	// is a process-global sync.Once, so an env change here would decide the
	// outcome for every later test in the package.
	empty := t.TempDir()
	_, _, err := resolveORT(filepath.Join(empty, "absent.so"), empty, empty, []string{empty})
	if err == nil {
		t.Fatal("expected an error when no library exists anywhere")
	}
	if !Unavailable(err) {
		t.Errorf("error is not ErrUnavailable: %T", err)
	}
	for _, want := range []string{"tried:", "ONNXRUNTIME_LIB"} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("message should mention %q: %q", want, err.Error())
		}
	}

	// The real resolver should find something on a machine that has ORT.
	if path, how, err := FindORT(); err == nil {
		t.Logf("resolved ORT at %s via %s", path, how)
	} else {
		t.Logf("no ORT on this machine: %v", err)
	}
}

// TestSystemStartsWithoutEmbedder is the Phase 3 exit criterion: with no runtime
// and no model, the system must come up, say why, and stay usable.
func TestSystemStartsWithoutEmbedder(t *testing.T) {
	// A ModelDir that does not exist makes this deterministic: the model is
	// resolved before ORT is touched, so the outcome does not depend on whether
	// this machine happens to have a runtime installed.
	s := openTestStore(t)
	sys := NewSystem(s, Config{ModelDir: filepath.Join(t.TempDir(), "absent")}, nil)
	defer sys.Close()

	if sys.EmbeddingsAvailable() {
		t.Fatal("embeddings reported available despite a nonexistent model directory")
	}
	reason := sys.UnavailableReason()
	if reason == "" {
		t.Fatal("no reason given for unavailable embeddings")
	}
	t.Logf("reason: %s", reason)

	// Ingestion still works — chunks are stored without vectors.
	root := writeVault(t)
	rep, err := sys.Ingester.IngestDirectory(context.Background(), root, nil)
	if err != nil {
		t.Fatalf("ingestion should work without an embedder: %v", err)
	}
	if rep.ChunksWritten == 0 {
		t.Fatal("no chunks written")
	}

	st, err := sys.Status()
	if err != nil {
		t.Fatal(err)
	}
	if st.EmbeddingsAvailable {
		t.Error("status disagrees with EmbeddingsAvailable")
	}
	if st.UnavailableReason == "" {
		t.Error("status omits the reason")
	}
	if st.Corpus.Chunks == 0 {
		t.Error("status reports no chunks despite a successful ingest")
	}
	if st.Corpus.EmbeddedChunks != 0 {
		t.Error("chunks were embedded without an embedder")
	}

	// Backfill and vector search report unavailability rather than crashing.
	if _, err := sys.Backfill(context.Background(), 0, nil); !Unavailable(err) {
		t.Errorf("Backfill error = %v, want ErrUnavailable", err)
	}
	if _, err := sys.SearchVector(context.Background(), "anything", 5); !Unavailable(err) {
		t.Errorf("SearchVector error = %v, want ErrUnavailable", err)
	}
	if _, err := sys.EnqueueBackfill(); !Unavailable(err) {
		t.Errorf("EnqueueBackfill error = %v, want ErrUnavailable", err)
	}
}

// ---------- backfill ----------

// TestBackfillAfterProvisioning is the other exit criterion: a corpus ingested
// before the model existed must embed correctly once it arrives.
func TestBackfillAfterProvisioning(t *testing.T) {
	s := openTestStore(t)

	// Start with no embedder at all.
	sys := NewSystem(s, Config{Embedder: nil, ModelDir: filepath.Join(t.TempDir(), "absent")}, nil)
	defer sys.Close()

	root := writeVault(t)
	rep, err := sys.Ingester.IngestDirectory(context.Background(), root, nil)
	if err != nil {
		t.Fatal(err)
	}
	if rep.ChunksWritten == 0 {
		t.Fatal("nothing ingested")
	}

	before, err := s.MemoryStats()
	if err != nil {
		t.Fatal(err)
	}
	if before.EmbeddedChunks != 0 {
		t.Fatalf("expected 0 embedded chunks before provisioning, got %d", before.EmbeddedChunks)
	}

	// The model "arrives": install an embedder without restarting.
	if err := sys.SetEmbedder(NewFakeEmbedder()); err != nil {
		t.Fatalf("SetEmbedder: %v", err)
	}
	if !sys.EmbeddingsAvailable() {
		t.Fatal("embeddings still unavailable after SetEmbedder")
	}

	var progressCalls int
	br, err := sys.Backfill(context.Background(), 16, func(done, total int) { progressCalls++ })
	if err != nil {
		t.Fatalf("Backfill: %v", err)
	}
	t.Log(br.String())

	if br.Chunks != before.Chunks {
		t.Errorf("backfilled %d chunks, want %d", br.Chunks, before.Chunks)
	}
	if br.Remaining != 0 {
		t.Errorf("Remaining = %d, want 0", br.Remaining)
	}
	if progressCalls == 0 {
		t.Error("progress callback never invoked")
	}

	after, err := s.MemoryStats()
	if err != nil {
		t.Fatal(err)
	}
	if after.EmbeddedChunks != after.Chunks {
		t.Errorf("embedded %d of %d chunks", after.EmbeddedChunks, after.Chunks)
	}
	if after.EmbedModel != "fake-hashing-embedder" {
		t.Errorf("EmbedModel = %q", after.EmbedModel)
	}

	// A second backfill is a no-op.
	br2, err := sys.Backfill(context.Background(), 16, nil)
	if err != nil {
		t.Fatal(err)
	}
	if br2.Chunks != 0 {
		t.Errorf("second backfill embedded %d chunks, want 0", br2.Chunks)
	}
}

// TestVectorSearchRanksSensibly closes the loop: embed, store, and rank in SQL.
func TestVectorSearchRanksSensibly(t *testing.T) {
	s := openTestStore(t)
	sys := NewSystem(s, Config{Embedder: NewFakeEmbedder()}, nil)
	defer sys.Close()

	root := t.TempDir()
	files := map[string]string{
		"duckdb.md": "# DuckDB\n\nThe application stores its sessions and chunks inside an " +
			"embedded DuckDB database file on local disk.\n",
		"leiden.md": "# Leiden\n\nLeiden community detection groups sentences into topically " +
			"coherent clusters for chunking purposes.\n",
		"cats.md": "# Cats\n\nMy cat Biscuit enjoys sitting in cardboard boxes and knocking " +
			"pens off the desk repeatedly.\n",
	}
	for name, body := range files {
		if err := os.WriteFile(filepath.Join(root, name), []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
	}

	if _, err := sys.Ingester.IngestDirectory(context.Background(), root, nil); err != nil {
		t.Fatal(err)
	}
	if _, err := sys.Backfill(context.Background(), 0, nil); err != nil {
		t.Fatal(err)
	}

	hits, err := sys.SearchVector(context.Background(), "which database stores the chunks", 3)
	if err != nil {
		t.Fatalf("SearchVector: %v", err)
	}
	if len(hits) == 0 {
		t.Fatal("no hits")
	}
	for i, h := range hits {
		t.Logf("%d. sim=%.4f %s — %s", i+1, h.Similarity, h.SourceRef, truncStr(h.Text, 50))
	}
	if hits[0].SourceRef != "duckdb.md" {
		t.Errorf("top hit = %s, want duckdb.md", hits[0].SourceRef)
	}
	// Similarities must be descending and in range.
	for i := range hits {
		if hits[i].Similarity < -1.001 || hits[i].Similarity > 1.001 {
			t.Errorf("similarity %v out of range", hits[i].Similarity)
		}
		if i > 0 && hits[i].Similarity > hits[i-1].Similarity+1e-9 {
			t.Errorf("hits not in descending similarity order")
		}
	}
	// Provenance is carried so the model can attribute a claim.
	if hits[0].Title == "" || hits[0].SourceType != "directory" {
		t.Errorf("hit lacks provenance: %+v", hits[0])
	}
}

// TestModelChangeClearsVectors guards the invariant that vector spaces are never
// mixed: swapping the model must invalidate existing vectors, not leave them to be
// compared against incompatible ones.
func TestModelChangeClearsVectors(t *testing.T) {
	s := openTestStore(t)
	sys := NewSystem(s, Config{Embedder: NewFakeEmbedder()}, nil)
	defer sys.Close()

	root := t.TempDir()
	if err := os.WriteFile(filepath.Join(root, "n.md"),
		[]byte("# Note\n\nSome content here that will be chunked and embedded for the test.\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if _, err := sys.Ingester.IngestDirectory(context.Background(), root, nil); err != nil {
		t.Fatal(err)
	}
	if _, err := sys.Backfill(context.Background(), 0, nil); err != nil {
		t.Fatal(err)
	}
	mid, _ := s.MemoryStats()
	if mid.EmbeddedChunks == 0 {
		t.Fatal("nothing embedded")
	}

	// Install a different model identity.
	if err := sys.SetEmbedder(&renamedFake{FakeEmbedder: NewFakeEmbedder(), name: "other-model"}); err != nil {
		t.Fatal(err)
	}
	after, _ := s.MemoryStats()
	if after.EmbeddedChunks != 0 {
		t.Errorf("EmbeddedChunks = %d after model change, want 0 — vectors from a "+
			"different model must not survive", after.EmbeddedChunks)
	}
	if after.Chunks != mid.Chunks {
		t.Errorf("chunks were deleted (%d -> %d); only vectors should be cleared",
			mid.Chunks, after.Chunks)
	}
}

type renamedFake struct {
	*FakeEmbedder
	name string
}

func (r *renamedFake) ModelName() string { return r.name }

func TestCheckDimensionsRejectsMismatch(t *testing.T) {
	s := openTestStore(t)
	sys := NewSystem(s, Config{Embedder: NewFakeEmbedder()}, nil)
	defer sys.Close()

	if err := sys.CheckDimensions(); err != nil {
		t.Fatalf("matching dims reported an error: %v", err)
	}

	sys.mu.Lock()
	sys.embedder = &wrongDims{FakeEmbedder: NewFakeEmbedder()}
	sys.mu.Unlock()
	if err := sys.CheckDimensions(); err == nil {
		t.Error("expected an error for a dimension mismatch")
	} else {
		t.Logf("reported: %v", err)
	}
}

type wrongDims struct{ *FakeEmbedder }

func (w *wrongDims) Dims() int { return 768 }

// ---------- the real embedder, when provisioned ----------

// TestONNXEmbedder exercises the in-process path when the model and runtime are
// both present. Skipped otherwise, so the suite runs anywhere.
func TestONNXEmbedder(t *testing.T) {
	paths, err := FindModel()
	if err != nil {
		t.Skipf("model not provisioned: %v", err)
	}
	emb, err := NewONNXEmbedder(ONNXConfig{ModelDir: paths.Dir, IntraOpThreads: 2})
	if err != nil {
		t.Skipf("ONNX embedder unavailable: %v", err)
	}
	defer emb.Close()
	ctx := context.Background()

	if emb.Dims() != EmbedDims {
		t.Errorf("dims = %d", emb.Dims())
	}

	vs, err := emb.EmbedPassages(ctx, []string{
		"The app stores sessions in an embedded DuckDB database file.",
		"Leiden community detection groups sentences by topic.",
		"My cat is named Biscuit and enjoys sitting in boxes.",
	})
	if err != nil {
		t.Fatalf("EmbedPassages: %v", err)
	}
	for i, v := range vs {
		if n := vecNorm(v); math.Abs(n-1) > 1e-5 {
			t.Errorf("vector %d norm = %v, want 1", i, n)
		}
	}

	q, err := emb.EmbedQuery(ctx, "what database does the app use?")
	if err != nil {
		t.Fatal(err)
	}
	sims := []float64{Cosine(q, vs[0]), Cosine(q, vs[1]), Cosine(q, vs[2])}
	t.Logf("query similarities: duckdb=%.4f leiden=%.4f cat=%.4f", sims[0], sims[1], sims[2])
	if sims[0] <= sims[1] || sims[0] <= sims[2] {
		t.Errorf("the DuckDB passage should rank first: %v", sims)
	}

	// The query prefix must actually change the vector — if it were dropped, this
	// would be ~1.0 and recall would silently suffer.
	bare, err := emb.EmbedPassages(ctx, []string{"what database does the app use?"})
	if err != nil {
		t.Fatal(err)
	}
	if c := Cosine(q, bare[0]); c > 0.999 {
		t.Errorf("query prefix had no effect (cos=%.5f)", c)
	}

	// Padding invariance: CLS pooling with a correct attention mask must give the
	// same vector regardless of batch padding. This is what validates the pooling
	// and mask handling without an external reference.
	single, err := emb.EmbedPassages(ctx, []string{"short text"})
	if err != nil {
		t.Fatal(err)
	}
	mixed, err := emb.EmbedPassages(ctx, []string{
		"short text",
		strings.Repeat("a much longer sentence that dominates the padded width ", 8),
	})
	if err != nil {
		t.Fatal(err)
	}
	if c := Cosine(single[0], mixed[0]); c < 0.99999 {
		t.Errorf("padding invariance broken (cos=%.6f) — pooling or masking is wrong", c)
	}

	// Over-long input must not error.
	if _, err := emb.EmbedPassages(ctx, []string{strings.Repeat("word ", 4000)}); err != nil {
		t.Errorf("over-long input failed: %v", err)
	}
	// Empty input.
	if vs, err := emb.EmbedPassages(ctx, []string{""}); err != nil {
		t.Errorf("empty input failed: %v", err)
	} else if math.Abs(vecNorm(vs[0])-1) > 1e-5 {
		t.Errorf("empty input norm = %v", vecNorm(vs[0]))
	}
}

// TestORTAPIVersionMatchesPinnedBinding guards the version floor against a silent bump.
//
// onnxruntime_go compiles ORT_API_VERSION in from its bundled header and gives no way to
// request less, so the *binding* decides the minimum ONNX Runtime a user needs. Phase 0
// shipped v1.31.0, which requests API 26 and therefore rejected Debian's ORT 1.21
// outright; the binding is now pinned to v1.19.0 (API 21) so the distro package works.
//
// The trap this test exists for: the binding's own version number does not track the API
// it requests — v1.19.0 asks for 21 and v1.20.0 asks for 22 — so a routine-looking
// dependency bump can raise the floor and break every Debian 13 user, with the failure
// appearing only at runtime on a machine that has the older library. Reading the header
// is the only reliable check.
func TestORTAPIVersionMatchesPinnedBinding(t *testing.T) {
	out, err := exec.Command("go", "list", "-m", "-f", "{{.Dir}}",
		"github.com/yalue/onnxruntime_go").Output()
	if err != nil {
		t.Skipf("cannot locate the binding module: %v", err)
	}
	header := filepath.Join(strings.TrimSpace(string(out)), "onnxruntime_c_api.h")
	src, err := os.ReadFile(header)
	if err != nil {
		t.Skipf("cannot read %s: %v", header, err)
	}

	m := regexp.MustCompile(`#define\s+ORT_API_VERSION\s+(\d+)`).FindSubmatch(src)
	if m == nil {
		t.Fatalf("no ORT_API_VERSION in %s", header)
	}
	got, err := strconv.Atoi(string(m[1]))
	if err != nil {
		t.Fatal(err)
	}
	t.Logf("pinned binding requests ORT_API_VERSION %d (floor: ORT %s)", got, MinORTVersion)

	if got != RequiredORTAPIVersion {
		t.Errorf("the binding requests ORT_API_VERSION %d but RequiredORTAPIVersion says %d.\n"+
			"If the binding was upgraded deliberately, update both constants and the README's "+
			"stated minimum — but note that raising the floor above 21 breaks Debian 13, whose "+
			"libonnxruntime1.21 package caps at API 21.", got, RequiredORTAPIVersion)
	}
	if got > 21 {
		t.Errorf("ORT_API_VERSION %d requires ONNX Runtime newer than 1.21, so the distro "+
			"package on Debian 13 will be rejected at InitializeEnvironment. Pin the binding "+
			"back down (v1.19.0 is the newest that requests 21).", got)
	}
}
