package store

import (
	"database/sql"
	"fmt"
	"os"
	"path/filepath"
	"testing"
)

// These tests are the Phase 0.5 upgrade gate: they exercise every read path the
// app depends on, so they can be run against the current driver to establish a
// baseline and then re-run after the go-duckdb v2 upgrade to prove the existing
// database still opens and reads correctly.
//
// There was no sessions.db on the development machine to migrate, so instead of
// testing against a one-off live file, buildFixture creates one through the real
// Store API. That is reproducible, safe to re-run, and (unlike a hand-copied
// file) can be regenerated by the old driver on demand — see
// TestLegacyFileOpens.

// buildFixture populates a Store with data covering every table and column that
// the app reads back, including the shapes most likely to break across a
// storage-format change: JSON-ish text, unicode, empty strings, and timestamps.
func buildFixture(t *testing.T, s *Store) (sessionID string) {
	t.Helper()

	sessionID, err := s.CreateSession("Upgrade fixture — Café naïve 中文")
	if err != nil {
		t.Fatalf("CreateSession: %v", err)
	}

	msgs := []NewMessage{
		{Role: "user", Content: "what database do we use?", Model: "qwen3.6-27b", Mode: "none", Pinned: true},
		{Role: "cot", Content: "The user is asking about persistence.\nDuckDB is embedded.", Model: "qwen3.6-27b", Mode: "deep", Pinned: false},
		{Role: "assistant", Content: "DuckDB, embedded — see `store/store.go`.", Model: "qwen3.6-27b", Mode: "none", Pinned: true},
		// tool_args holds JSON as TEXT. This is the row that would expose the
		// v2 JSON-type scanning change if the column were typed JSON.
		{Role: "tool", Content: "", ToolName: "manage_plan", Pinned: false,
			ToolArgs:   `{"steps":[{"content":"Verify upgrade","status":"in_progress"},{"content":"Ship it","status":"pending"}]}`,
			ToolResult: "Plan updated (2 steps):\n1. [in_progress] Verify upgrade\n"},
		// Empty content and unicode, both legal and both worth round-tripping.
		{Role: "user", Content: "", Pinned: false},
		{Role: "assistant", Content: "emoji 🎉 — accents é ü — quotes \"nested\" 'single'", Pinned: true},
	}
	for i, m := range msgs {
		if _, err := s.SaveMessage(sessionID, m); err != nil {
			t.Fatalf("SaveMessage %d: %v", i, err)
		}
	}

	if _, err := s.CreateArtifact(sessionID, "Notes — résumé", "# Heading\n\nBody with `code` and a tab\there.", "markdown"); err != nil {
		t.Fatalf("CreateArtifact: %v", err)
	}
	if _, err := s.CreateArtifact(sessionID, "script.py", "print('hello')\n", "python"); err != nil {
		t.Fatalf("CreateArtifact 2: %v", err)
	}

	if err := s.SetPlan(sessionID, []PlanStep{
		{Seq: 1, Content: "Verify upgrade", Status: "in_progress"},
		{Seq: 2, Content: "Ship it", Status: "pending"},
	}); err != nil {
		t.Fatalf("SetPlan: %v", err)
	}
	return sessionID
}

// verifyFixture asserts every read path returns what buildFixture wrote. Run
// against both the old and new driver; any divergence is an upgrade regression.
func verifyFixture(t *testing.T, s *Store, sessionID string) {
	t.Helper()

	sessions, err := s.GetSessions()
	if err != nil {
		t.Fatalf("GetSessions: %v", err)
	}
	var found *Session
	for i := range sessions {
		if sessions[i].ID == sessionID {
			found = &sessions[i]
		}
	}
	if found == nil {
		t.Fatalf("session %s missing from GetSessions (%d sessions)", sessionID, len(sessions))
	}
	if found.Title != "Upgrade fixture — Café naïve 中文" {
		t.Errorf("title round-trip failed: %q", found.Title)
	}
	// GetSessions counts only user/assistant rows: 3 user/assistant pinned +
	// 1 empty user + ... = 4 (2 user with content + 1 empty user + ... ) —
	// computed explicitly rather than hardcoded to keep the intent visible.
	if found.MessageCount != 4 {
		t.Errorf("MessageCount = %d, want 4 (user+assistant rows only)", found.MessageCount)
	}
	if found.CreatedAt == "" {
		t.Error("CreatedAt empty — timestamp scan regression")
	}

	got, err := s.GetMessages(sessionID)
	if err != nil {
		t.Fatalf("GetMessages: %v", err)
	}
	if len(got) != 6 {
		t.Fatalf("GetMessages returned %d rows, want 6", len(got))
	}
	if got[0].Seq != 1 || got[5].Seq != 6 {
		t.Errorf("seq ordering wrong: first=%d last=%d", got[0].Seq, got[5].Seq)
	}
	if got[1].Role != "cot" || got[1].Pinned {
		t.Errorf("cot row wrong: role=%q pinned=%v", got[1].Role, got[1].Pinned)
	}
	// The JSON-as-TEXT check.
	tool := got[3]
	if tool.ToolName != "manage_plan" {
		t.Errorf("tool_name = %q", tool.ToolName)
	}
	if tool.ToolArgs == "" || tool.ToolArgs[0] != '{' {
		t.Errorf("tool_args did not round-trip as plain TEXT: %q", tool.ToolArgs)
	}
	if !contains(tool.ToolArgs, `"status":"in_progress"`) {
		t.Errorf("tool_args content altered: %q", tool.ToolArgs)
	}
	if got[4].Content != "" {
		t.Errorf("empty content became %q", got[4].Content)
	}
	if !contains(got[5].Content, "🎉") || !contains(got[5].Content, "é") {
		t.Errorf("unicode content mangled: %q", got[5].Content)
	}
	if got[5].Time == "" {
		t.Error("message timestamp empty")
	}

	arts, err := s.GetArtifactsForSession(sessionID)
	if err != nil {
		t.Fatalf("GetArtifactsForSession: %v", err)
	}
	if len(arts) != 2 {
		t.Fatalf("artifacts = %d, want 2", len(arts))
	}
	full, err := s.GetArtifact(arts[0].ID)
	if err != nil {
		t.Fatalf("GetArtifact: %v", err)
	}
	if full.SessionID != sessionID || full.Content == "" {
		t.Errorf("artifact round-trip wrong: %+v", full)
	}

	plan, err := s.GetPlan(sessionID)
	if err != nil {
		t.Fatalf("GetPlan: %v", err)
	}
	if len(plan) != 2 || plan[0].Status != "in_progress" || plan[1].Status != "pending" {
		t.Errorf("plan wrong: %+v", plan)
	}

	has, err := s.HasMessages(sessionID)
	if err != nil || !has {
		t.Errorf("HasMessages = %v, %v", has, err)
	}
}

func contains(s, sub string) bool {
	for i := 0; i+len(sub) <= len(s); i++ {
		if s[i:i+len(sub)] == sub {
			return true
		}
	}
	return false
}

// openStoreAt opens a Store against an explicit path, mirroring what Open does
// but without its cwd-dependent path discovery.
func openStoreAt(t *testing.T, path string) *Store {
	t.Helper()
	db, err := sql.Open("duckdb", path)
	if err != nil {
		t.Fatalf("open duckdb %s: %v", path, err)
	}
	s := &Store{db: db}
	if _, err := db.Exec(schemaSQL); err != nil {
		db.Close()
		t.Fatalf("create tables: %v", err)
	}
	return s
}

// TestFullRoundTrip is the baseline: write everything, read everything back.
func TestFullRoundTrip(t *testing.T) {
	path := filepath.Join(t.TempDir(), "round-trip.db")
	s := openStoreAt(t, path)
	defer s.Close()

	sessionID := buildFixture(t, s)
	verifyFixture(t, s, sessionID)
}

// TestReopenPersistedFile closes the database and reopens it from disk, which is
// what actually exercises the on-disk storage format rather than an in-memory
// cache. This is the test whose behavior across the version change matters.
func TestReopenPersistedFile(t *testing.T) {
	path := filepath.Join(t.TempDir(), "reopen.db")

	s := openStoreAt(t, path)
	sessionID := buildFixture(t, s)
	if err := s.Close(); err != nil {
		t.Fatalf("close: %v", err)
	}

	s2 := openStoreAt(t, path)
	defer s2.Close()
	verifyFixture(t, s2, sessionID)
}

// TestLegacyFileOpens reads a database file produced by the PREVIOUS driver
// version, which is the actual forward-compatibility gate from the plan's
// §3.0. Generate the fixture with the old driver before upgrading:
//
//	LEGACY_DB_OUT=/tmp/legacy-1.1.3.db go test ./store -run TestGenerateLegacyFixture
//
// then after the upgrade:
//
//	LEGACY_DB=/tmp/legacy-1.1.3.db go test ./store -run TestLegacyFileOpens
func TestLegacyFileOpens(t *testing.T) {
	path := os.Getenv("LEGACY_DB")
	if path == "" {
		t.Skip("set LEGACY_DB to a database written by the previous driver version")
	}
	if _, err := os.Stat(path); err != nil {
		t.Fatalf("LEGACY_DB %s: %v", path, err)
	}

	// Copy first: opening may upgrade the file in place, and we want the
	// original left intact for repeat runs.
	tmp := filepath.Join(t.TempDir(), "legacy-copy.db")
	if err := copyFile(path, tmp); err != nil {
		t.Fatalf("copy: %v", err)
	}

	db, err := sql.Open("duckdb", tmp)
	if err != nil {
		t.Fatalf("open legacy file: %v", err)
	}
	s := &Store{db: db}
	defer s.Close()

	var sessionID string
	if err := db.QueryRow(
		`SELECT id FROM sessions WHERE title LIKE 'Upgrade fixture%' LIMIT 1`,
	).Scan(&sessionID); err != nil {
		t.Fatalf("legacy file did not yield the fixture session: %v", err)
	}
	verifyFixture(t, s, sessionID)
	t.Logf("legacy database at %s opened and verified", path)
}

// TestGenerateLegacyFixture is a generator, not an assertion: run it under the
// OLD driver to produce a file for TestLegacyFileOpens to read under the new one.
func TestGenerateLegacyFixture(t *testing.T) {
	out := os.Getenv("LEGACY_DB_OUT")
	if out == "" {
		t.Skip("set LEGACY_DB_OUT to write a legacy-format fixture")
	}
	os.Remove(out)

	s := openStoreAt(t, out)
	sessionID := buildFixture(t, s)
	verifyFixture(t, s, sessionID)
	if err := s.Close(); err != nil {
		t.Fatalf("close: %v", err)
	}

	var v string
	db, _ := sql.Open("duckdb", out)
	defer db.Close()
	_ = db.QueryRow("SELECT version()").Scan(&v)
	fi, _ := os.Stat(out)
	t.Logf("wrote %s (%d bytes) with DuckDB %s, session %s", out, fi.Size(), v, sessionID)
}

func copyFile(src, dst string) error {
	b, err := os.ReadFile(src)
	if err != nil {
		return err
	}
	return os.WriteFile(dst, b, 0o644)
}

var _ = fmt.Sprintf
