// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';
import {skill} from '../models';
import {main} from '../models';

export function CreateArtifactManual(arg1:string,arg2:string,arg3:string):Promise<string>;

export function CreateSession():Promise<string>;

export function DeleteSession(arg1:string):Promise<void>;

export function GetArtifactContent(arg1:string):Promise<store.Artifact>;

export function GetArtifacts(arg1:string):Promise<Array<store.ArtifactMeta>>;

export function GetCotMode():Promise<string>;

export function GetCurrentSession():Promise<string>;

export function GetMessages(arg1:string):Promise<Array<store.StoredMessage>>;

export function GetModel():Promise<string>;

export function GetSessions():Promise<Array<store.Session>>;

export function GetSkillBody(arg1:string):Promise<string>;

export function ListCotModes():Promise<Array<string>>;

export function ListModels():Promise<Array<string>>;

export function ListSkills():Promise<Array<skill.Meta>>;

export function RenameSession(arg1:string,arg2:string):Promise<void>;

export function SaveMessage(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SendChat(arg1:string,arg2:Array<main.ChatMessage>,arg3:string):Promise<main.ChatTurnResult>;

export function SetCotMode(arg1:string):Promise<void>;

export function SetMessagePinned(arg1:string,arg2:number,arg3:boolean):Promise<void>;

export function SetModel(arg1:string):Promise<void>;

export function SwitchSession(arg1:string):Promise<void>;
