// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';
import {main} from '../models';

export function CreateSession():Promise<string>;

export function DeleteSession(arg1:string):Promise<void>;

export function GetCotMode():Promise<string>;

export function GetCurrentSession():Promise<string>;

export function GetMessages(arg1:string):Promise<Array<store.StoredMessage>>;

export function GetModel():Promise<string>;

export function GetSessions():Promise<Array<store.Session>>;

export function ListCotModes():Promise<Array<string>>;

export function ListModels():Promise<Array<string>>;

export function RenameSession(arg1:string,arg2:string):Promise<void>;

export function SaveMessage(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SendChat(arg1:string,arg2:Array<main.ChatMessage>):Promise<string>;

export function SetCotMode(arg1:string):Promise<void>;

export function SetModel(arg1:string):Promise<void>;

export function SwitchSession(arg1:string):Promise<void>;
