// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearDirectory() {
  return window['go']['main']['App']['ClearDirectory']();
}

export function CreateArtifactManual(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateArtifactManual'](arg1, arg2, arg3);
}

export function CreateSession() {
  return window['go']['main']['App']['CreateSession']();
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function GetArtifactContent(arg1) {
  return window['go']['main']['App']['GetArtifactContent'](arg1);
}

export function GetArtifacts(arg1) {
  return window['go']['main']['App']['GetArtifacts'](arg1);
}

export function GetCotMode() {
  return window['go']['main']['App']['GetCotMode']();
}

export function GetCurrentSession() {
  return window['go']['main']['App']['GetCurrentSession']();
}

export function GetMessages(arg1) {
  return window['go']['main']['App']['GetMessages'](arg1);
}

export function GetModel() {
  return window['go']['main']['App']['GetModel']();
}

export function GetSessions() {
  return window['go']['main']['App']['GetSessions']();
}

export function GetSkillBody(arg1) {
  return window['go']['main']['App']['GetSkillBody'](arg1);
}

export function GetWorkDir() {
  return window['go']['main']['App']['GetWorkDir']();
}

export function ListCotModes() {
  return window['go']['main']['App']['ListCotModes']();
}

export function ListModels() {
  return window['go']['main']['App']['ListModels']();
}

export function ListSkills() {
  return window['go']['main']['App']['ListSkills']();
}

export function RenameSession(arg1, arg2) {
  return window['go']['main']['App']['RenameSession'](arg1, arg2);
}

export function SaveMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveMessage'](arg1, arg2, arg3);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SendChat(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendChat'](arg1, arg2, arg3);
}

export function SetCotMode(arg1) {
  return window['go']['main']['App']['SetCotMode'](arg1);
}

export function SetMessagePinned(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetMessagePinned'](arg1, arg2, arg3);
}

export function SetModel(arg1) {
  return window['go']['main']['App']['SetModel'](arg1);
}

export function SwitchSession(arg1) {
  return window['go']['main']['App']['SwitchSession'](arg1);
}
