// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearDirectory() {
  return window['go']['main']['App']['ClearDirectory']();
}

export function CreateArtifactManual(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateArtifactManual'](arg1, arg2, arg3);
}

export function CreateSession() {
  return window['go']['main']['App']['CreateSession']();
}

export function DefaultMemoryWeights() {
  return window['go']['main']['App']['DefaultMemoryWeights']();
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function EnrichMemoryEntities(arg1) {
  return window['go']['main']['App']['EnrichMemoryEntities'](arg1);
}

export function ForgetMemoryFolder(arg1) {
  return window['go']['main']['App']['ForgetMemoryFolder'](arg1);
}

export function ForgetMemorySource(arg1) {
  return window['go']['main']['App']['ForgetMemorySource'](arg1);
}

export function GetArtifactContent(arg1) {
  return window['go']['main']['App']['GetArtifactContent'](arg1);
}

export function GetArtifacts(arg1) {
  return window['go']['main']['App']['GetArtifacts'](arg1);
}

export function GetCotMode() {
  return window['go']['main']['App']['GetCotMode']();
}

export function GetCurrentSession() {
  return window['go']['main']['App']['GetCurrentSession']();
}

export function GetMemoryModelInfo() {
  return window['go']['main']['App']['GetMemoryModelInfo']();
}

export function GetMessages(arg1) {
  return window['go']['main']['App']['GetMessages'](arg1);
}

export function GetModel() {
  return window['go']['main']['App']['GetModel']();
}

export function GetPlan(arg1) {
  return window['go']['main']['App']['GetPlan'](arg1);
}

export function GetSessionToolStates(arg1) {
  return window['go']['main']['App']['GetSessionToolStates'](arg1);
}

export function GetSessions() {
  return window['go']['main']['App']['GetSessions']();
}

export function GetSkillBody(arg1) {
  return window['go']['main']['App']['GetSkillBody'](arg1);
}

export function GetWorkDir() {
  return window['go']['main']['App']['GetWorkDir']();
}

export function ImportArtifact(arg1) {
  return window['go']['main']['App']['ImportArtifact'](arg1);
}

export function IndexExistingHistory() {
  return window['go']['main']['App']['IndexExistingHistory']();
}

export function IngestDirectory(arg1) {
  return window['go']['main']['App']['IngestDirectory'](arg1);
}

export function ListCotModes() {
  return window['go']['main']['App']['ListCotModes']();
}

export function ListModels() {
  return window['go']['main']['App']['ListModels']();
}

export function ListSkills() {
  return window['go']['main']['App']['ListSkills']();
}

export function MemoryReady() {
  return window['go']['main']['App']['MemoryReady']();
}

export function MemorySources() {
  return window['go']['main']['App']['MemorySources']();
}

export function MemoryStatus() {
  return window['go']['main']['App']['MemoryStatus']();
}

export function ProvisionMemoryModel() {
  return window['go']['main']['App']['ProvisionMemoryModel']();
}

export function RebuildMemoryEdges() {
  return window['go']['main']['App']['RebuildMemoryEdges']();
}

export function RenameSession(arg1, arg2) {
  return window['go']['main']['App']['RenameSession'](arg1, arg2);
}

export function RollbackMemoryEntityEnrichment() {
  return window['go']['main']['App']['RollbackMemoryEntityEnrichment']();
}

export function SaveArtifact(arg1) {
  return window['go']['main']['App']['SaveArtifact'](arg1);
}

export function SaveMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveMessage'](arg1, arg2, arg3);
}

export function SearchMemoryManual(arg1, arg2) {
  return window['go']['main']['App']['SearchMemoryManual'](arg1, arg2);
}

export function SearchMemoryTuned(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchMemoryTuned'](arg1, arg2, arg3);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectMemoryDirectory() {
  return window['go']['main']['App']['SelectMemoryDirectory']();
}

export function SendChat(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendChat'](arg1, arg2, arg3, arg4);
}

export function SetCotMode(arg1) {
  return window['go']['main']['App']['SetCotMode'](arg1);
}

export function SetMessagePinned(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetMessagePinned'](arg1, arg2, arg3);
}

export function SetModel(arg1) {
  return window['go']['main']['App']['SetModel'](arg1);
}

export function SetSessionToolEnabled(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetSessionToolEnabled'](arg1, arg2, arg3);
}

export function SwitchSession(arg1) {
  return window['go']['main']['App']['SwitchSession'](arg1);
}

export function UnindexedHistoryCount() {
  return window['go']['main']['App']['UnindexedHistoryCount']();
}
