// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {store} from '../models';
import {skill} from '../models';
import {memory} from '../models';

export function ClearDirectory():Promise<void>;

export function CreateArtifactManual(arg1:string,arg2:string,arg3:string):Promise<string>;

export function CreateSession():Promise<string>;

export function DefaultMemoryWeights():Promise<main.MemorySearchTuning>;

export function DeleteSession(arg1:string):Promise<void>;

export function EnrichMemoryEntities(arg1:number):Promise<boolean>;

export function ForgetMemoryFolder(arg1:string):Promise<number>;

export function ForgetMemorySource(arg1:string):Promise<void>;

export function GetArtifactContent(arg1:string):Promise<store.Artifact>;

export function GetArtifacts(arg1:string):Promise<Array<store.ArtifactMeta>>;

export function GetCotMode():Promise<string>;

export function GetCurrentSession():Promise<string>;

export function GetMemoryModelInfo():Promise<main.MemoryModelInfo>;

export function GetMessages(arg1:string):Promise<Array<store.StoredMessage>>;

export function GetModel():Promise<string>;

export function GetPlan(arg1:string):Promise<Array<store.PlanStep>>;

export function GetSessionGenOptions(arg1:string):Promise<store.GenOptions>;

export function GetSessionToolStates(arg1:string):Promise<Array<main.ToolState>>;

export function GetSessions():Promise<Array<store.Session>>;

export function GetSkillBody(arg1:string):Promise<string>;

export function GetWorkDir():Promise<string>;

export function ImportArtifact(arg1:string):Promise<store.ArtifactMeta>;

export function IndexExistingHistory():Promise<boolean>;

export function IngestDirectory(arg1:string):Promise<boolean>;

export function ListCotModes():Promise<Array<string>>;

export function ListModels():Promise<Array<string>>;

export function ListSkills():Promise<Array<skill.Meta>>;

export function MemoryReady():Promise<boolean>;

export function MemorySources():Promise<Array<store.MemorySource>>;

export function MemoryStatus():Promise<memory.Status>;

export function ModelContextLength(arg1:string):Promise<number>;

export function ProvisionMemoryModel():Promise<boolean>;

export function RebuildMemoryEdges():Promise<boolean>;

export function RenameSession(arg1:string,arg2:string):Promise<void>;

export function RollbackMemoryEntityEnrichment():Promise<number>;

export function SaveArtifact(arg1:string):Promise<string>;

export function SaveMessage(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SearchMemoryManual(arg1:string,arg2:number):Promise<Array<memory.Result>>;

export function SearchMemoryTuned(arg1:string,arg2:number,arg3:main.MemorySearchTuning):Promise<main.MemorySearchResponse>;

export function SelectDirectory():Promise<string>;

export function SelectMemoryDirectory():Promise<string>;

export function SendChat(arg1:string,arg2:Array<main.ChatMessage>,arg3:string,arg4:string):Promise<main.ChatTurnResult>;

export function SetCotMode(arg1:string):Promise<void>;

export function SetMessagePinned(arg1:string,arg2:number,arg3:boolean):Promise<void>;

export function SetModel(arg1:string):Promise<void>;

export function SetSessionGenOptions(arg1:string,arg2:store.GenOptions):Promise<void>;

export function SetSessionToolEnabled(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SwitchSession(arg1:string):Promise<void>;

export function UnindexedHistoryCount():Promise<number>;
